sudo: false
language: node_js
notifications:
  email: false
node_js:
  - '0.10'
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
  - curl -Lo travis_after_all.py https://git.io/vLSON
after_success:
  - python travis_after_all.py
  - export $(cat .to_export_back)
env:
  matrix:
  - NODE=0.10 COMMAND=test:browser:cloud
  - NODE=0.12 COMMAND=test:browser:cloud
  - NODE=4.0 COMMAND=test:browser:cloud
  - NODE=iojs-v1 COMMAND=test:browser:cloud
  - NODE=iojs-v2 COMMAND=test:browser:cloud
