ui: tape
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  # https://github.com/hoodiehq/pouchdb-hoodie-store/issues/13
  # - name: ie
  #   version: latest
  - name: iphone
    version: latest
  - name: android
    version: latest
